name: ✨ Feautre Report
description: Suggest an idea for this project
title: "[Feature] "
labels: ["✨ Feature"]
body:
  - type: textarea
    attributes:
      label: 🌈 Background
      description: 해당 이슈를 생성하게된 이유가 무엇인가요?
      placeholder: 뭐든지 적어주세요~
    validations:
      required: true

  - type: textarea
    attributes:
      label: 📋 Todo
      description: 해야할 일들이 무엇인가요?
      placeholder: "- [ ] 이렇게 체크박스 생성해서 적으시면 됩니다~"

  - type: textarea
    attributes:
      label: 👀 See Also
      description: 추가적으로 작성할 것이 있나요?
